---
title: "Branding and Product Promise"
---

<br>

### Adherence to Criteria

Prosthetic Rehabilitation for Optimized Versatility (P.R.O.V.) was named under multiple criteria for the strongest memorable impact on the target market, while also being an available name in its domain. The slogan “Move freely, live fully.” is also available in this domain. 

- Easy to spell

  * Clear, short, and has no “hidden” letters in the pronunciation

- Easy to recognize / remember 

  * Being an acronym allows for better remembrance

- Pronounce easily and only one way

  * The name is pronounced phonetically, making it clear and easy to say

- Consistent with image

  * Image and logo matches brand theme and products

- Not generic

  * While it may be short, it is not a common name used in branding 

- Available 

  * Legally available for use, as a domain name, and with no confusion between it and another brand

- Not offensive, negative, obscene

  * It does not have any negative meaning or translation

- Selling suggestion (here is your promise)

  * Promise shown through “V” for versatility

- Has cachet (has appeal without connection to brand)

  * Can sound and look like “prove” which gives an initial positive influence to the consumer

- Always Timely

  * Will not go out of style as it is not specific to this era of time

- Travels well (other cultures & languages)

  * Only is related to French and Latin descents with the translation of “to prove”

---

### Product Promise

P.R.O.V. has created the promise of providing unique, durable, and affordable prosthetics and orthotics to its customers. It sets a high standard for customer satisfaction by incorporating long-term payment plans for lower income households and prioritising sustainable and long lasting products. 

---

[← Back to Table of Contents](mark_business_plan.html)

[← Back to Home](index.html)