---
title: "Value Chain"
---

<br>

### Dissatisfaction with Competitor’s Brand

Because this product category uses custom parts and fittings for different consumers as well as requiring complex design and programming components, it can be very costly. However, the majority of the competitors in the field of prosthetic and orthotic manufacturing do not provide accommodations for lower income households. 

While it is becoming more common in the current environmental state of the world, not all brands use sustainable methods when producing their products. Even with the products’ lifespan increasing, the impact from producing the materials outways the positives.

With this product category involving high-priced products, there is an expectation for high durability and length of use. While some brands will have high-endurance products, they are specific to activities that require this level of endurance; not all of their products are built to last as long as their athletic-based products. 

### Product Planning

In order to have the highest output for consumers, P.R.O.V. has taken initiatives to practice sustainability in their production methods. To do this they are using environmentally friendly approaches specifically in the design and assembly process of production. P.R.O.V. has also made multiple different payment plans, including partial payments over a period of time for all products, allowing for consumers in a lower income household to receive the same level of care as other consumers. While production of prosthetics and orthotics is expensive, quality is one of the most important factors to consider. With this in mind, P.R.O.V. is planning to produce high-durability and increased lifespan options for all of their products.

### Buying Motives

- More accessible payment plans to provide care in every household.
- Sustainable production methods.
- High durability options for every product.

### Explanation of Links

P.R.O.V.’s research team has looked into reviews of dissatisfactions for items in the product category and taken the feedback into account when planning for production. This is in order to expand the target market and increase customer satisfaction.

---

[← Back to Table of Contents](mark_business_plan.html)

[← Back to Home](index.html)